# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeCare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeCare
  pod 'Firebase/Auth'

  target 'WeCareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeCareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

     pod 'Firebase/Core'
     pod 'Firebase/Database'
     pod 'Firebase/Auth'	
     pod 'GoogleSignIn'	
     pod 'FBSDKCoreKit'
     pod 'FBSDKShareKit'
     pod 'FBSDKLoginKit'

end
